import { Footer } from "@/shared/components/shared/footer"
import { Header } from "@/shared/components/shared/header"

import type { Metadata } from "next"

export const metadata: Metadata = {
	title: "MIRA FOOD | Главная странница",
	description: "Generated by human hands :P",
	keywords: "Pizza, Food, Kaliningrad, Best Food, Best Pizza",
	icons: "/logo.png",
}

export default function RootLayout({
	children,
	modal,
}: Readonly<{
	children: React.ReactNode
	modal: React.ReactNode
}>) {
	return (
		<main className="min-h-screen">
			<Header />
			{children}
			{modal}
			<Footer />
		</main>
	)
}
