import { Header } from "@/shared/components/shared/header"
import { MainLoader } from "@/shared/components/shared/main-loader"

import type { Metadata } from "next"
import { Suspense } from "react"

export const metadata: Metadata = {
	title: "MIRA FOOD | Главная странница",
	description: "Generated by human hands :P",
	keywords: "Pizza, Food, Kaliningrad, Best Food, Best Pizza",
	icons: "/logo.png",
}

export default function RootLayout({
	children,
	modal,
}: Readonly<{
	children: React.ReactNode
	modal: React.ReactNode
}>) {
	return (
		<MainLoader>
			<main className="min-h-screen">
				<Suspense>
					<Header />
				</Suspense>
				{children}
				{modal}
			</main>
		</MainLoader>
	)
}
